apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-ui
  template:
    metadata:
      labels:
        app: static-ui
    spec:
      containers:
      - name: static-ui
        image: <your-dockerhub-username>/static-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: GRAPHQL_ENDPOINT
          value: "http://35.238.156.18:80/"  # Set your actual endpoint here
---
apiVersion: v1
kind: Service
metadata:
  name: static-ui-service
spec:
  selector:
    app: static-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
