apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-ui
  template:
    metadata:
      labels:
        app: static-ui
    spec:
      containers:
      - name: static-ui
        image: sumanth17121988/simple-ui:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-ui-service
spec:
  selector:
    app: static-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
